### ISSUE TITLE
Initial screen freeze and hang

### ISSUE THREAD

**Issue by methylene** [bartobri/no-more-secrets#1]
Compiling it was a breeze, but when runnings `ls -l | bin/nms` it gets stuck after printing the initial screen line by line.

Somehow github can't attach a .png so I'll paste the contents of the frozen screen below.
````
wE!36 3w
no!,YwitB= y |88 !YA &}{.S &I$ @+ @xA>Q {<uTKWx
E0_&++-v3e o ^^t 1&M   )dl Jj] aV [:RaB 1|OFtE1\
(RWx"3Ztg? h aj: 6Wl  +(8> dZH FA xYsb- tZZ,%32Zg
2*u\qI6oR< u FM+ OR,  bYpZ .?V n& #;cL] Ty%
1?1Q02ppza C )22 -+|  7EoI V(z oG @U@Yw Xcc
2u68[2r6g] G <8A ,&"  G]hf :ql f% {o%[R H%H
````

**Comment by bartobri** [comment]
Thanks for the feedback. I assume you pressed a key and it was still hung? If so, what system and you running it on?

**Comment by methylene** [comment]
Yes, I pressed CRTL-C, but as I've now learned, any other key will start the animation. Thank you! Is there also an option to run it automatically, without the extra key press?

**Comment by bartobri** [comment]
Okay, glad it is working. No I didn't make an option for it to start automatically, but that is simple enough to do so I may add that feature. In the movie clip, however, they press a key to start the "decryption" sequence. So that is why I built it that way.

**Comment by homeworkprod** [comment]
For the record: The `nms` binary now supports the `-a` option to not wait for a key press before the animation starts.
