### ISSUE TITLE
Tag a release

### ISSUE THREAD

**Issue by zi0r** [bartobri/no-more-secrets#12]
Please tag a release for port maintainers!

**Comment by MoritzFago** [comment]
also required for homebrew!

**Comment by bartobri** [comment]
Okay, tagged a release: v0.1.0

Never tagged a release before so let me know if this is what you needed or if you need something else.

**Comment by apjanke** [comment]
Looks good, and works for a Homebrew formula. I've submitted a PR for one. https://github.com/Homebrew/homebrew-core/pull/752

Hat tip to The Changelog Weekly for pointing me at this project. Very neat!

**Comment by bartobri** [comment]
Successfully created tag. Closing this issue.
