### ISSUE TITLE
create basic website

### ISSUE THREAD

**Issue by MoritzFago** [bartobri/no-more-secrets#13]
to be acceptable as a formula for homebrew `no-more-secrets` needs some kind of homepage, could you possible add a simple one? Just a simple gh-pages is enough.

**Comment by apjanke** [comment]
Nope. As long as you have a decent README or other documentation in the repo itself, the GitHub repo page can serve as a project's home page for Homebrew's purposes.

**Comment by bartobri** [comment]
Okay good :) That would be my preference. I assume my README page is sufficient. Closing this issue. @MoritzFago Let me know if you have any concerns that merit reopening this issue.
