### ISSUE TITLE
Add parameter for setting speed

### ISSUE THREAD

**Issue by korczis** [bartobri/no-more-secrets#18]
It will be nice to have parameter which can be used for tweaking "processing" speed.

**Comment by bartobri** [comment]
Hi @korczis. There are several speed parameters in the code (nms.c):

#define TYPE_EFFECT_SPEED    4
#define JUMBLE_SECONDS       2
#define JUMBLE_LOOP_SPEED    35
#define REVEAL_LOOP_SPEED    100

These can be tweaked and recompiled to your liking.

Adding parameters for each setting would be messy. The goal of the project is to match the speed shown in the movie.

Thanks,
Brian
