### ISSUE TITLE
Feature request: command line options

### ISSUE THREAD

**Issue by jakimfett** [bartobri/no-more-secrets#2]
I'd like to request the ability to skip the pauses (as mentioned [here](https://github.com/bartobri/no-more-secrets#using-the-standalone-executable) when executing the program via a command line flag, eg `cat somefile.txt | bin/nms --no-pause`.

**Comment by bartobri** [comment]
Hi and thanks for the interest. So I have two pauses. The first one can possibly be skipped (maybe making it sleep for a second or two for effect), but the second pause is necessary for the user to actually read what the text says, otherwise it would immediately disappear after displaying. And in the case of displaying a menu, the pause is necessary to get user input.

**Comment by jakimfett** [comment]
Ah, good point. Would it be possible to add a flag for just the first pause, so that text is displayed garbled, then immediately run through the "decrypting" effect?

A bit about what I'm trying to do...I have an old style typewriter hooked up to a raspberry pi, running a shell script that activates one of the GPIO pins when the correct key phrase is typed in. When incorrect input is typed in, the script will just display some variation of "incorrect input, please try again", but when the correct key phrase is typed in, some story type text gets printed on the screen after "decrypting" via the no-more-secrets effect.

**Comment by bartobri** [comment]
Skipping the first pause via command line option should be pretty easy to do. I'll add that option when I have some time.

**Comment by jakimfett** [comment]
Fantastic! Do you have a Patreon or Paypal donation option? I'd like to send you a bit of a financial "thank you", this is a really fun little utility!

**Comment by bartobri** [comment]
Not necessary but thanks for the offer :)

**Comment by kryptonianson** [comment]
I would like the ability to set the speed of the "decryption" process on the command line. It is a bit too slow for me.

**Comment by shaneog** [comment]
Rather than `--no-pause`, how about `--auto-decrypt` for clarity?

**Comment by jakimfett** [comment]
Works for me. I'm less concerned about *what* I type in, as long as it allows me to eliminate the pause.

@kryptonianson maybe open a new ticket for your additional, completely different, feature request?

**Comment by apjanke** [comment]
Could we also get a `-v` or `--version` to output the version number instead of doing the effect display? Would be useful for Homebrew or other packagers, where we like to do at least a trivial execution test to confirm the executable was built and linked correctly.

**Comment by bartobri** [comment]
@kryptonianson Look in nms.c and play around with the speed settings and see if you can get what you want. Just change the number for the setting and type 'make' again.

#define TYPE_EFFECT_SPEED    4
#define JUMBLE_SECONDS       2
#define JUMBLE_LOOP_SPEED    35
#define REVEAL_LOOP_SPEED    100

**Comment by bartobri** [comment]
@jakimfett Just committed changes to support the -a command line option which skips the first pause and auto-starts the decryption effect. Give it a try.

ls -l | nms -a

**Comment by bartobri** [comment]
@apjanke Just committed changes to support the -v command line option which prints the version number.

**Comment by apjanke** [comment]
Works as expected for `-v`.

```
$ ./bin/nms -v
nms version 0.1.0
```

Thanks!

**Comment by bartobri** [comment]
All issues addressed. Closing.
