### ISSUE TITLE
libncurses regression on macOS

### ISSUE THREAD

**Issue by ilovezfs** [bartobri/no-more-secrets#24]
https://github.com/bartobri/no-more-secrets/commit/9d7ac87af302ebe913190b56f10de1bfe3032ba1 has introduced a regression on macOS where the library is named libncurses not libncursesw:

```
gcc -Wextra -Wall -o obj/main.o -c src/main.c
gcc -Wextra -Wall -o bin/nms obj/nms.o obj/main.o -lncursesw
gcc -Wextra -Wall -o bin/sneakers obj/nms.o obj/sneakers.o -lncursesw
ld: library not found for -lncursesw
ld: library not found for -lncursesw
clang: error: linker command failed with exit code 1 (use -v to see invocation)
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [sneakers] Error 1
make: *** Waiting for unfinished jobs....
make: *** [nms] Error 1
```

**Comment by bartobri** [comment]
Hi @ilovezfs, ncursesw is needed to support wide characters. I don't have Mac OS X. Is this library not available on Mac? Every linux machine I tested has it. Seems like Mac should have it as well...

**Comment by bartobri** [comment]
Perhaps ncursesw has to be installed as a dependency first?

**Comment by c256** [comment]
The ncurses that comes standard in macOs has wide character support built in. Put another way, ncurses on macOS (from the OS) *is* ncursesw. The change needed is to the Makefile (use -lncurses instead of -lncursesw), not to the source.

Hope this helps.

**Comment by bartobri** [comment]
@ilovezfs @c256 I just pushed a change 0496a3f. Can you please test it and let me know if it fixes this issue? If so, i'll tag a new release. Also let me know if you have any concerns.

Thanks!

**Comment by c256** [comment]
That works for me on 10.11.5. Thanks!

**Comment by bartobri** [comment]
Okay thanks. I'll consider this issue fixed. I tagged a new release, v0.2.1, which contains this fix.

**Comment by ilovezfs** [comment]
@bartobri Yep, looks good. I was just able to remove both patches from the formula. However, one minor issue did come up:
```
==> /usr/local/Cellar/no-more-secrets/0.2.1/bin/nms -v
Error: no-more-secrets: failed
<"nms version 0.2.1"> expected but was
<"nms version 0.2.0">.
```

**Comment by bartobri** [comment]
@ilovezfs Woops. I forgot to update the version number in the code. This has been fixed now.

Thanks.

**Comment by ilovezfs** [comment]
no problem!

**Comment by ilovezfs** [comment]
@bartobri : so much better https://github.com/Homebrew/homebrew-core/pull/2959

:)
