### ISSUE TITLE
Add project to homebrew

### ISSUE THREAD

**Issue by andersfischernielsen** [bartobri/no-more-secrets#3]
Awesome project! 

It'd be really cool to have it on homebrew, that'll make it easier to get for most people. 

https://github.com/Homebrew/brew/blob/master/share/doc/homebrew/Formula-Cookbook.md

**Comment by bartobri** [comment]
Thanks for the compliment!

If someone wants to add it to homebrew, that's cool with me. I don't think I'll have the time to do it myself though. Thanks for the suggestion!

**Comment by stacybird** [comment]
Can the issue stay open since that way other folks can see this is work to be done, and pick it up?   

https://github.com/Homebrew/brew/blob/master/share/doc/homebrew/Formula-Cookbook.md#basic-instructions

**Comment by MoritzFago** [comment]
the next step, after tagging a release is a homepage, like i mentioned in #13.

**Comment by apjanke** [comment]
Hi! Homebrew maintainer here. I really dig this project, so I put in a formula PR for it myself. https://github.com/Homebrew/homebrew-core/pull/752

Normally Homebrew [requires a project repo to be at least a month old](https://github.com/Homebrew/brew/blob/master/share/doc/homebrew/Acceptable-Formulae.md), but for highly popular repos there can be exceptions. We'll probably make one here. Alternately, young projects can just [create your own tap](https://github.com/Homebrew/brew/blob/master/share/doc/homebrew/How-to-Create-and-Maintain-a-Tap.md) for the first couple months of a project, before submitting to core Homebrew.

As long as you have a decent README, the GitHub repo page can serve as a home page for the project.

**Comment by apjanke** [comment]
...and you're in. Mac Homebrew users can now install No More Secrets with `brew update; brew install no-more-secrets`.

Glad to see the interest in Homebrew!

**Comment by bartobri** [comment]
Thanks @apjanke !! Glad you like the project, and thanks for your time adding this to homebrew :)

I assume I can close this issue then. Let me know if I need to reopen it for whatever reason.
