### ISSUE TITLE
No animation neither 'decryption' effect (openSUSE)

### ISSUE THREAD

**Issue by elnomade** [bartobri/no-more-secrets#30]
I followed the instructions to install no-more-secrets from source and from package. Same results for both. When you run sneakers or nms you get the 'encrypted' characters and nothing else, no animation and no decryption effect.
No compilation error (from source) neither any installation error (from package).

OS: openSUSE Tumbleweed.

**Comment by bartobri** [comment]
Hello. As noted in the README file:

> Once the "encrypted" data is displayed, the program will pause until you press a key. Then the decryption effect will start. After that is completed, it will again pause until you press a key, at which point the program will terminate.

You can also use the -a command switch to auto-start the encryption effect.

`ls -l / | nms -a`

Let me know if you continue to have problems.

**Comment by elnomade** [comment]
Thanks for your quick answer.
I tested this tool in different OSes, OpenSUSE is working fine, but OSX El Capitan is having some issues. I will create a new issue.

**Comment by bartobri** [comment]
Have you followed the documented install procedure for OS X?

https://github.com/bartobri/no-more-secrets/blob/master/INSTALL.md#mac-osx

This is the only approved method for installing on Mac at this time.

**Comment by homeworkprod** [comment]
> Once the "encrypted" data is displayed, the program will pause until you press a key.
Oh my, I did overlook that one, too, and assumed a bug :(
