### ISSUE TITLE
if it "decrypts" one character it should "decrypt" every instance of that character

### ISSUE THREAD

**Issue by ehartford** [bartobri/no-more-secrets#31]
repro steps:

echo thing1 thing2 thing3 | nms

expected: 
  the t's all "decrypt" at the same step, the h's all "decrypt" at the same step, etc.

observed: nope.

![image](https://cloud.githubusercontent.com/assets/1117701/18618325/68ffff64-7ddc-11e6-9ce4-28caafbb14bb.png)

**Comment by bartobri** [comment]
Hi and thanks for your interest.

I don't think your expectation is valid. All characters are meant to decrypt at their own individual pace just as it appears in the film. Closing this issue.

Thanks.

**Comment by RogerThiede** [comment]
I'm a big fan of Sneakers.  However I don't know the details of how the effect was designed in the movie.  Can you cite evidence in how no-more-secrets was designed?  Possibly add those details to the README.md?

**Comment by bartobri** [comment]
Hi Roger.

I don't claim to have insider knowledge of how the effect was created for
the film, nor use any such information for my project. My project is simply
a visual recreation of what we see in the film.

Thanks,
Brian
