### ISSUE TITLE
Switches -a and -f not working in El Capitan 

### ISSUE THREAD

**Issue by elnomade** [bartobri/no-more-secrets#34]
OS: Mac OS X El Capitan.
Installation: brew

Switches -a and -f not working as described in documentation.

-a should automatically start effect
-f should change font color

How to reproduce:
* Install no-more-secrets from brew, open a terminal, pick "Basic" from settings, 
type: brew install no-more-secrets

* type: ls -lh /opt | nms -a   (application will wait for a key press instead of automatically starts)

* type: ls -lh /opt | nms -f green
   then press a key, wait for decryption effect, then you will notice that color doesn't change to green.

Video: https://youtu.be/QUNjFaupQeQ

**Comment by IWriteThings** [comment]
Just built from source in El Capitan 10.11.6.

Fully functional with both -a and -f. Perhaps the brew install needs some work?

**Comment by bartobri** [comment]
Thanks for helping, @IWriteThings 

Closing this issue.
