### ISSUE TITLE
Using it for the MOTD banner

### ISSUE THREAD

**Issue by shadycuz** [bartobri/no-more-secrets#35]
So I thought it would be cool to invoke this upon shh login. It works kinda, the problem I have is it doesn't like my banner for some reason and I don't like the blue text. Maybe in the future you can make an option to let it keep the terminal fg colors? 

```

echo -e "\e[32m                                         \e[97m       __         \e[39m"
echo -e "\e[32m                                                \e[97m      /_/\        \e[39m"
echo -e "\e[32m  ____  _               _                       \e[97m     / /\ \       \e[39m"
echo -e "\e[32m / ___|| |__   __ _  __| |_   _  ___ _   _ ____ \e[97m    / / /\ \      \e[39m"
echo -e "\e[32m \___ \| |_ \ / _  |/ _| | | | |/ __| | | |_  / \e[97m   / / /\ \ \     \e[39m"
echo -e "\e[32m  ___) | | | | (_| | (_| | |_| | (__| |_| |/ /  \e[97m  / /_/__\ \ \    \e[39m"
echo -e "\e[32m |____/|_| |_|\__,_|\__,_|\__, |\___|\__,_/___| \e[97m /_/______\_\/\   \e[39m"
echo -e "\e[32m                          |___/                 \e[97m \_\_________\/   \e[39m \n"
echo -e "\e[92mHostname....:\e[39m \e[34m`hostname`\e[39m"
echo -e "\e[92mOS..........:\e[39m \e[34m${OSSTR}\e[39m\e[31m ${MOTD_KERNEL}\e[39m"
echo -e "\e[92mIPv4........:${MOTD_MYIPADDR}"
echo -e "\e[92mDate........:\e[39m \e[34m`date`\e[39m"
echo -e "\e[92mLoad........:\e[39m \e[34m${MOTD_LOADAVG}\e[39m"
echo -e "\e[92mMemory......:\e[39m \e[34m${MOTD_MEMPERC}\e[39m \e[92mpercent used\e[39m"
echo -e "\e[92mNet Use.....:\e[39m \e[34m${MOTD_NETMONTH}\e[39m\e[31m ${MOTD_NETMONTHS} \e[39m\e[92mused this month\e[39m"
echo -e "\e[92mUptime......:\e[39m \e[34m${MOTD_UPTIME}\e[39m \e[92mdays\e[39m"
echo -e "${MOTD_WHO}"
echo -e "${MOTD_LASTLOGIN}"
```

I only see the bottom text and they have huge spaces in between the lines where there shouldn't be. Hold the phone, I got it work, had to make the terminal bigger. but I see it exactly as I see it above with all the formating like [92m . Be nice if we could find a way to make it work. landscape-sysinfo works great. I guess for now I might just take all the colors I use out.

Thanks for the cool thingy.

**Comment by bartobri** [comment]
> Maybe in the future you can make an option to let it keep the terminal fg colors?

I believe i looked in to it once and found that the pipe removed the color characters so that nms had no knowledge of them. But it is on my list to look at again. Perhaps in the next version. I agree, it would be nice.

>I don't like the blue text

There is a command line option to change the foreground color. See the README file.
