### ISSUE TITLE
Please refer to the docker image

### ISSUE THREAD

**Issue by freiit** [bartobri/no-more-secrets#39]
Sad that you closed [the pull request](https://github.com/bartobri/no-more-secrets/pull/37). I think, things should stick together.

Anyways, I moved the Dockerfile into a new [github repository](https://github.com/freiit/no-more-secrets-docker) and pushed it to hub.docker.com [here](https://hub.docker.com/r/freiit/no-more-secrets-docker/).

Would you mind to refer to it, so people can pick up on this, if they want to drive without installation or work around not supported OS like Windows?

Thanks, \C

**Comment by bartobri** [comment]
Hello again. I really do appreciate your interest but there i no need to support docker images by including an extra file specifically for docker. Supporting specific docker configurations is outside of the scope of this project. Those who know how to use docker can simply follow the existing install instructions to run nms without the need for a superfluous docker file.

Here is an example of how someone can launch nms in docker:

docker run --rm -it debian bash -c "\
apt update && apt install -y --no-install-recommends build-essential ca-certificates git ncurses-dev && \
git clone https://github.com/bartobri/no-more-secrets.git && cd no-more-secrets && make && \
ls -l / | bin/nms"

**Comment by bartobri** [comment]
I've linked to your repository form the INSTALL doc for those who may be interested in a dockerfile.
