### ISSUE TITLE
"make install" target broken on macOS in 0.3.1

### ISSUE THREAD

**Issue by ilovezfs** [bartobri/no-more-secrets#46]
```
==> make prefix=/usr/local/Cellar/no-more-secrets/0.3.1 install
install -d /usr/local/Cellar/no-more-secrets/0.3.1/share/man/man6
install -m644 -t /usr/local/Cellar/no-more-secrets/0.3.1/share/man/man6 nms.6 sneakers.6
install: illegal option -- t
usage: install [-bCcpSsv] [-B suffix] [-f flags] [-g group] [-m mode]
               [-o owner] file1 file2
       install [-bCcpSsv] [-B suffix] [-f flags] [-g group] [-m mode]
               [-o owner] file1 ... fileN directory
       install -d [-v] [-g group] [-m mode] [-o owner] directory ...
make: *** [install] Error 64
```

This was not broken in 0.3.0.

Build log here: https://bot.brew.sh/job/Homebrew%20Core/16712/version=sierra/consoleText

**Comment by bartobri** [comment]
@susnux Can we install the man pages without the use of the -t option? This is causing an issue on OSX.

**Comment by susnux** [comment]
Of cause, if you do not mind I create a pull request fixing this.

**Comment by bartobri** [comment]
@ilovezfs Can you confirm this is fixed? Do you need me to create another release?

**Comment by ilovezfs** [comment]
@bartobri yes, but I've discovered a new bug now :)
```
iMac-TMP:~ joe$ brew test no-more-secrets
Testing no-more-secrets
==> Using the sandbox
==> /usr/local/Cellar/no-more-secrets/0.3.1/bin/nms -v
Error: no-more-secrets: failed
<"nms version 0.3.1"> expected but was
<"nms version 0.3.0">.
```

**Comment by ilovezfs** [comment]
>Do you need me to create another release?

A new release also with the matching version number would be great.

**Comment by bartobri** [comment]
Woops! That's not the first time I've forgotten to increment the software version number to match a new release. Sorry about that.

I've created a new release (0.3.2) with matching version number. Please confirm all is working as expected.

**Comment by ilovezfs** [comment]
Looks like we're good: https://github.com/Homebrew/homebrew-core/pull/10142

**Comment by bartobri** [comment]
Great! Thanks!

**Comment by ilovezfs** [comment]
Thanks for the quick turnaround! New version shipped.
