### ISSUE TITLE
Foreign characters

### ISSUE THREAD

**Issue by agucova** [bartobri/no-more-secrets#49]
Hey!
It seems that characters like the tilde or a ñ (from spanish), keep their character instead of being revealed.
<img width="420" alt="noooo" src="https://cloud.githubusercontent.com/assets/4694408/23484850/76289514-feb7-11e6-9ba8-22983e01e519.png">

**Comment by bartobri** [comment]
Hi @agucova 

I can not reproduce this issue. Can you provide the exact text you are using as input? Also, did you compile this from source? If so, did you install the default program or did you choose the ncurses version?

- Brian

**Comment by bartobri** [comment]
No response. Can not reproduce. Closing this.
