### ISSUE TITLE
Extra character(s) for 1 and 2 character lines

### ISSUE THREAD

**Issue by neuhaus** [bartobri/no-more-secrets#50]
If you have an output line consisting of 

    .:

the nms tool will add an extra "r" character on the line. During the animation the "r" will remain constant. It will not disappear after the "decryption".

Try it using

    echo ".:" | ./bin/nms

PS: Quick testing reveals that I get this error for all lines consisting of two characters. For lines that only contain one character, I get two bogus "r" characters.

I'm on Ubuntu 16.04.

**Comment by bartobri** [comment]
Fixed in commit ff5fbbd7

- Brian
