### ISSUE TITLE
src/nmstermio.c:162: newbie error with EOF ?

### ISSUE THREAD

**Issue by dcb314** [bartobri/no-more-secrets#54]
src/nmstermio.c:162]: (warning) Storing getchar() return value in char variable and then comparing with EOF.

The return value from getchar should be stored in an int. See http://c-faq.com/stdio/getcharc.html
for details.

**Comment by bartobri** [comment]
Newbie comment aside, thanks for finding this. This is fixed with commit 39c02de5. The fix has been pushed to the master branch.
