### ISSUE TITLE
Feature Wish: Parameter to set "decryption" speed

### ISSUE THREAD

**Issue by hilbrichtsoftware** [bartobri/no-more-secrets#57]
It would be very nice to have an option to specify how long it should take. Maybe even two parameters: How long until the scrambled chars are written and then how long it takes to decrypt. With 0 being instantaneous.

**Comment by bartobri** [comment]
Hi. Thanks for your interest in my project.

This requests has come through a couple times, and each time I decline to implement it on the basis that it is the intent of this project to recreate what is in the film. This applies to the timing of the decryption sequence.

However, if you wish, you can modify the timing of the decryption sequence in the source code by adjusting the value of the following constants prior to running 'make'. These can be found in the source file nmseffect.c.

#define TYPE_EFFECT_SPEED    4     // miliseconds per char
#define JUMBLE_SECONDS       2     // number of seconds for jumble effect
#define JUMBLE_LOOP_SPEED    35    // miliseconds between each jumble
#define REVEAL_LOOP_SPEED    50    // miliseconds between each reveal loop

The TYPE_EFFECT_SPEED setting is one of the options you are looking for. The other 3 options, in combination, will control the speed at which the characters are decrypted.

Thanks,
Brian
