### ISSUE TITLE
Wront phrase

### ISSUE THREAD

**Issue by afarber** [bartobri/no-more-secrets#58]
The correct phrase from the Sneakers movie is:

Setec Astronomy -> Too many secrets

(and not "No more secrets")     :)

**Comment by bartobri** [comment]
You are correct that the anagram spells "too many secrets" but the phrase "no more secrets" is the title of the scene where we first see the effect. It is what Bishop says at the end of the scene when he realizes what the black box can do. The phrase is also said a few other times throughout the movie in reference to it's decryption capabilities.
