### ISSUE TITLE
'sneakers' command only works once

### ISSUE THREAD

**Issue by byamj** [bartobri/no-more-secrets#61]
~~Executing the `sneakers` command works the first time, but running it a second time in the same iTerm session throws `Abort trap: 6`. Quitting and restarting iTerm allows it to be run one more time before throwing the same error.~~

This based on window size, I wasn't careful when attempting to reproduce.

Executing the `sneakers` command works with window width 242 but not 243 and throws `Abort trap: 6`. Number gathered from resizing my iTerm window and looking at the status bar. Height doesn't seem to matter.

Edit the second: It's not the absolute size, it seems to be the ratio between height and width that causes the error.

System:
macOS Sierra version 10.12.6

**Comment by bartobri** [comment]
@byamj , do you experience this issue with a smaller terminal size? I think it is the sheer size of your terminal that is causing my program to write past the buffer limit. It's a legit bug on my end. But first let me know if you can reproduce with smaller terminal sizes.

Thanks.

**Comment by byamj** [comment]
With a window height of 2, 246 is the widest the window can be without causing an error. Window height 60 also works at 246 width but not 247 so I think that's the magic number.

**Comment by bartobri** [comment]
This is fixed in commit 56df5f3d and pushed to the master branch.

@byamj can you pull the latest code from the master branch, recompile, and confirm that it is fixed for you?

Thanks!

**Comment by byamj** [comment]
Confirmed to be fixed at width 247 through 270/fullscreen.
