### ISSUE TITLE
Please indicate GPL version

### ISSUE THREAD

**Issue by QuLogic** [bartobri/no-more-secrets#64]
Everything states this is "under the terms of the GPL License", but it does not state a version. The `LICENSE` is GPLv3, but it is not clearly stated whether the code is under "v3" or "v3 or later".

**Comment by QuLogic** [comment]
I recommend using the [full text of the suggested license notice](https://www.gnu.org/licenses/gpl-howto.html).

**Comment by bartobri** [comment]
Everything says to see LICENSE for details. The LICENSE file clear states GPLv3. I am not sure what is causing your confusion. Closing this.
