### ISSUE TITLE
Error while "make sneakers"

### ISSUE THREAD

**Issue by Taavettiii** [bartobri/no-more-secrets#66]
I can't seem to get the `make sneakers` command to work.

I am using your [instructions](https://github.com/bartobri/no-more-secrets#download-and-install)

Here's the output of the command:
`[taavi@laptop no-more-secrets]$ make sneakers
cc -Wextra -Wall -O2 -o obj/sneakers.o -c src/sneakers.c
src/sneakers.c: In function ‘main’:
src/sneakers.c:183:25: warning: pointer targets in passing argument 1 of ‘nmseffect_exec’ differ in signedness [-Wpointer-sign]
  input = nmseffect_exec(display);
                         ^~~~~~~
In file included from src/sneakers.c:12:
src/nmseffect.h:12:6: note: expected ‘unsigned char *’ but argument is of type ‘char *’
 char nmseffect_exec(unsigned char *, int string_len);
      ^~~~~~~~~~~~~~
src/sneakers.c:183:10: error: too few arguments to function ‘nmseffect_exec’
  input = nmseffect_exec(display);
          ^~~~~~~~~~~~~~
In file included from src/sneakers.c:12:
src/nmseffect.h:12:6: note: declared here
 char nmseffect_exec(unsigned char *, int string_len);
      ^~~~~~~~~~~~~~
make: *** [Makefile:37: obj/sneakers.o] Error 1`
What's wrong?

**Comment by bartobri** [comment]
This is my fault. I made some module changes and didn't update the sneakers program. This should be fixed now. Please pull the latest code from master (git pull origin master) and try running Make nms again. Or just delete everything and redo the install instructions.
