### ISSUE TITLE
adding | nms to the end of the command "ls -lahR" does the same thing as ls -a | nms

### ISSUE THREAD

**Issue by LemonHeadOnGit** [bartobri/no-more-secrets#67]
Hi there.
So I tried using the | nms tool after the huge and amazing command, "ls -lahR" (which lists all the directories on the computer), and I found out it gives the exact same output as "ls -a | nms". Is this something in the code that limits it, or is there something wrong?
Thanks
~L

**Comment by bartobri** [comment]
Hi @LemonHeadOnGit 

The code intentionally truncates input to fit the height of the terminal.

Thanks for the interest.

- Brian

**Comment by LemonHeadOnGit** [comment]
oh ok thanks
