### ISSUE TITLE
No transparency support?

### ISSUE THREAD

**Issue by Skarlett** [bartobri/no-more-secrets#73]
running the application creates a custom background (black) and then runs the text manipulation. You show on your example that it can use transparent terminals - This doesn't seem to be the effect for me.

Terminal emulator - gnome

**Comment by bartobri** [comment]
Hi @Skarlett 

Transparency is controlled by your terminal emulator, not the programs running within it. If transparency is not working in your terminal you should check the terminal settings. This program does not have the ability to change background colors. It can only change text color (if you choose the option). Any issues you have with the background color must be coming from your terminal.

Thanks
Brian
