### ISSUE TITLE
Speed flag for auto-decrypt

### ISSUE THREAD

**Issue by reesericci** [bartobri/no-more-secrets#75]
Is there any way you can implement a speed flag for auto-decrypt? I'd like to be able to make the "decryption" faster.

**Comment by bartobri** [comment]
Hi @reesericci 

Thats not on my list of to-dos. The intent is to match the speed of the movie. But if you want, you can decrease (not increase) the JUMBLE_LOOP_SPEED and REVEAL_LOOP_SPEED settings in nmseffect.c before running sudo make install and that will increase the decryption speed. Play around with them until you get what you want.

Thanks for the interest.
