### ISSUE TITLE
Extra characters

### ISSUE THREAD

**Issue by rockedsocks** [bartobri/no-more-secrets#77]
Whenever I do anything involving the text decryption, it always adds a few extra characters on the end. The characters are both encrypted and decrypted. Usually the decrypted ones are  all the same letter if they are on the same line. Though I have noticed that when using lolcat (changes a command's output to be rainbow) it seems to make it instead of change the same line, create a new line for each "frame". When this is done it works perfectly fine, though with 12 billion lines generated.

**Comment by bartobri** [comment]
Hello. Please provide more details. What OS are you using? What terminal app are you using? What is the full command you are typing? A screenshot would also be helpful.

**Comment by bartobri** [comment]
No response from reporter. Closing.
