### ISSUE TITLE
does not work properly with non-english locale

### ISSUE THREAD

**Issue by tuanhtrng** [bartobri/no-more-secrets#8]
I am using Vietnamese locale on this machine and nms fails to render some characters.

**Comment by apjanke** [comment]
This is probably more about Unicode multibyte UTF-8 characters than locale/region per se. #7 looks like the same issue.

**Comment by bartobri** [comment]
@tuanhtrng I've just pushed support for UTF-8 characters. Can you please test and let me know if it works now?

**Comment by bartobri** [comment]
No response. Closing.
