### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by mikelolasagasti** [bartobri/no-more-secrets#82]
There have been some PRs merged since last release in 2017. Would it be possible to have a new release so downstream doesn't have to carry patches?

**Comment by bartobri** [comment]
Good call. Didn't realize it had been that long. Just tagged a release: https://github.com/bartobri/no-more-secrets/releases/tag/v1.0.0

**Comment by bartobri** [comment]
Just tagged another release because I didn't update the version inside the code to match the github release. Use this one: https://github.com/bartobri/no-more-secrets/releases/tag/v1.0.1
