### ISSUE TITLE
Piping an echo command into nms causes a segmentation fault (Core dumped).

### ISSUE THREAD

**Issue by CES-2005** [bartobri/no-more-secrets#87]
I recently installed Arch Linux. This is not my first time doing so, but I am facing a problem when piping stdin into nms. When I run `nms` and then type input, the program works as expected. However, when I try `echo "test" | nms`, my terminal prints "Segmentation fault (core dumped)". My terminal then has the text `1R` despite my not typing it. Sometimes it have a semicolon instead: `;1R`

**Comment by CES-2005** [comment]
After some testing, it turns out this issue only occurs when chrooted. When I run the command on the actual machine, it works correctly. I get the segmentation fault when I run `nms` while chrooted into the Arch system from my other Arch installation.

**Comment by bartobri** [comment]
Closing. Looks like a user environment issue.
