### ISSUE TITLE
anyway to make it not disappear/terminate?

### ISSUE THREAD

**Issue by shaunstanislaus** [bartobri/no-more-secrets#9]
was wondering if there is anyway to make it not terminated after running it?

**Comment by bartobri** [comment]
The screen clearing is an automatic function of ncurses. I do not see an option to disable it.

**Comment by ZeroChaos-** [comment]
I can't reopen this issue but this can be solved with a pretty simple combination of things.

1.) store input
2.) act on input (doing cool stuff)
3.) drop ncurses and just echo out the stored input

This would only work if you formatted the data in the same way as the input (ls for instance shows up multiline in nms but one line without) and drop the blue to stick with the normal input colors.

just a thought, this would make this a lot better.

**Comment by ZeroChaos-** [comment]
might be a bit hard since ncurses clears the screen, I'm not sure how to deal with that except to actually clear the screen when returning and before echoing out the input.
